"""
Client automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

import requests
import sdkgen
from requests import RequestException
from typing import List
from typing import Dict
from typing import Any
from urllib.parse import parse_qs

from .completions_tag import CompletionsTag
from .responses_tag import ResponsesTag

class Client(sdkgen.ClientAbstract):
    def __init__(self, base_url: str, credentials: sdkgen.CredentialsInterface):
        super().__init__(base_url, credentials)

    def completions(self) -> CompletionsTag:
        return CompletionsTag(
            self.http_client,
            self.parser
        )

    def responses(self) -> ResponsesTag:
        return ResponsesTag(
            self.http_client,
            self.parser
        )



    @staticmethod
    def build(token: str):
        return Client("https://api.openai.com", sdkgen.HttpBearer(token))


    @staticmethod
    def buildAnonymous():
        return Client("https://api.openai.com", sdkgen.Anonymous())
