"""
completion_tokens_details automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union


class CompletionTokensDetails(BaseModel):
    accepted_prediction_tokens: Optional[int] = Field(default=None, alias="accepted_prediction_tokens")
    audio_tokens: Optional[int] = Field(default=None, alias="audio_tokens")
    reasoning_tokens: Optional[int] = Field(default=None, alias="reasoning_tokens")
    rejected_prediction_tokens: Optional[int] = Field(default=None, alias="rejected_prediction_tokens")
    pass


