"""
completion_choice automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
from .completion_message import CompletionMessage


class CompletionChoice(BaseModel):
    index: Optional[int] = Field(default=None, alias="index")
    message: Optional[CompletionMessage] = Field(default=None, alias="message")
    finish_reason: Optional[str] = Field(default=None, alias="finish_reason")
    pass


