"""
completion_deleted automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union


class CompletionDeleted(BaseModel):
    object: Optional[str] = Field(default=None, alias="object")
    id: Optional[str] = Field(default=None, alias="id")
    deleted: Optional[bool] = Field(default=None, alias="deleted")
    pass


