"""
completion_collection automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
from .completion_response import CompletionResponse


class CompletionCollection(BaseModel):
    object: Optional[str] = Field(default=None, alias="object")
    data: Optional[List[CompletionResponse]] = Field(default=None, alias="data")
    first_id: Optional[str] = Field(default=None, alias="first_id")
    last_id: Optional[str] = Field(default=None, alias="last_id")
    has_more: Optional[bool] = Field(default=None, alias="has_more")
    pass


