"""
completion_usage automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
from .completion_tokens_details import CompletionTokensDetails
from .prompt_tokens_details import PromptTokensDetails


class CompletionUsage(BaseModel):
    completion_tokens: Optional[int] = Field(default=None, alias="completion_tokens")
    prompt_tokens: Optional[int] = Field(default=None, alias="prompt_tokens")
    total_tokens: Optional[int] = Field(default=None, alias="total_tokens")
    completion_tokens_details: Optional[CompletionTokensDetails] = Field(default=None, alias="completion_tokens_details")
    prompt_tokens_details: Optional[PromptTokensDetails] = Field(default=None, alias="prompt_tokens_details")
    pass


