"""
completion_message automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
from .completion_message_developer import CompletionMessageDeveloper
from .completion_message_system import CompletionMessageSystem
from .completion_message_user import CompletionMessageUser
from .completion_message_assistant import CompletionMessageAssistant
from .completion_message_tool import CompletionMessageTool


class CompletionMessage(BaseModel):
    role: Optional[str] = Field(default=None, alias="role")
    content: Optional[List[str]] = Field(default=None, alias="content")
    pass


