"""
completion_message_assistant automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
from .completion_message import CompletionMessage


class CompletionMessageAssistant(CompletionMessage):
    audio: Optional[str] = Field(default=None, alias="audio")
    name: Optional[str] = Field(default=None, alias="name")
    refusal: Optional[str] = Field(default=None, alias="refusal")
    tool_calls: Optional[List[str]] = Field(default=None, alias="tool_calls")
    pass


