"""
completion_response automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
from .completion_choice import CompletionChoice
from .completion_usage import CompletionUsage


class CompletionResponse(BaseModel):
    id: Optional[str] = Field(default=None, alias="id")
    object: Optional[str] = Field(default=None, alias="object")
    created: Optional[int] = Field(default=None, alias="created")
    model: Optional[str] = Field(default=None, alias="model")
    choices: Optional[List[CompletionChoice]] = Field(default=None, alias="choices")
    usage: Optional[CompletionUsage] = Field(default=None, alias="usage")
    service_tier: Optional[str] = Field(default=None, alias="service_tier")
    system_fingerprint: Optional[str] = Field(default=None, alias="system_fingerprint")
    pass


