"""
completion_message_tool automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
from .completion_message import CompletionMessage


class CompletionMessageTool(CompletionMessage):
    tool_call_id: Optional[str] = Field(default=None, alias="tool_call_id")
    pass


