"""
ErrorException automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

import sdkgen
from typing import Dict
from typing import Any

from .error import Error

class ErrorException(sdkgen.KnownStatusCodeException):
    payload: Error = None

    def __init__(self, payload):
        self.payload = payload

    def get_payload(self) -> Error:
        return self.payload
