"""
prompt_tokens_details automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union


class PromptTokensDetails(BaseModel):
    audio_tokens: Optional[int] = Field(default=None, alias="audio_tokens")
    cached_tokens: Optional[int] = Field(default=None, alias="cached_tokens")
    pass


