"""
response_reasoning automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union


class ResponseReasoning(BaseModel):
    effort: Optional[str] = Field(default=None, alias="effort")
    summary: Optional[str] = Field(default=None, alias="summary")
    pass


