"""
response_text_format_json_schema automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
from .response_text_format import ResponseTextFormat


class ResponseTextFormatJsonSchema(ResponseTextFormat):
    name: Optional[str] = Field(default=None, alias="name")
    schema_: Optional[Any] = Field(default=None, alias="schema")
    type: Optional[str] = Field(default=None, alias="type")
    description: Optional[str] = Field(default=None, alias="description")
    strict: Optional[bool] = Field(default=None, alias="strict")
    pass


