"""
response_request_input_function_call_output automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
from .response_request_input import ResponseRequestInput


# The output of a function tool call.
class ResponseRequestInputFunctionCallOutput(ResponseRequestInput):
    call_id: Optional[str] = Field(default=None, alias="call_id")
    output: Optional[str] = Field(default=None, alias="output")
    type: Optional[str] = Field(default="function_call_output", alias="type")
    id: Optional[str] = Field(default=None, alias="id")
    status: Optional[str] = Field(default=None, alias="status")
    pass


