"""
response_mcp_tool automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union


class ResponseMCPTool(BaseModel):
    input_schema: Optional[Any] = Field(default=None, alias="input_schema")
    name: Optional[str] = Field(default=None, alias="name")
    annotations: Optional[Dict[str, str]] = Field(default=None, alias="annotations")
    description: Optional[str] = Field(default=None, alias="description")
    pass


