"""
response_tool_mcp automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
from .response_tool import ResponseTool


class ResponseToolMCP(ResponseTool):
    server_label: Optional[str] = Field(default=None, alias="server_label")
    type: Optional[str] = Field(default=None, alias="type")
    allowed_tools: Optional[List[str]] = Field(default=None, alias="allowed_tools")
    authorization: Optional[str] = Field(default=None, alias="authorization")
    connector_id: Optional[str] = Field(default=None, alias="connector_id")
    headers: Optional[Dict[str, str]] = Field(default=None, alias="headers")
    require_approval: Optional[str] = Field(default=None, alias="require_approval")
    server_description: Optional[str] = Field(default=None, alias="server_description")
    server_url: Optional[str] = Field(default=None, alias="server_url")
    pass


