"""
response_tool_web_search automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
from .response_tool import ResponseTool
from .response_tool_web_search_filter import ResponseToolWebSearchFilter
from .response_tool_web_search_location import ResponseToolWebSearchLocation


class ResponseToolWebSearch(ResponseTool):
    type: Optional[str] = Field(default="web_search", alias="type")
    filters: Optional[ResponseToolWebSearchFilter] = Field(default=None, alias="filters")
    search_context_size: Optional[str] = Field(default=None, alias="search_context_size")
    user_location: Optional[ResponseToolWebSearchLocation] = Field(default=None, alias="user_location")
    pass


