"""
response_text_format_text automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
from .response_text_format import ResponseTextFormat


class ResponseTextFormatText(ResponseTextFormat):
    type: Optional[str] = Field(default="text", alias="type")
    pass


