"""
response_prompt automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union


class ResponsePrompt(BaseModel):
    id: Optional[str] = Field(default=None, alias="id")
    variables: Optional[Dict[str, str]] = Field(default=None, alias="variables")
    version: Optional[str] = Field(default=None, alias="version")
    pass


