"""
response_response_output_function_call automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union


class ResponseResponseOutputFunctionCall(BaseModel):
    arguments: Optional[str] = Field(default=None, alias="arguments")
    call_id: Optional[str] = Field(default=None, alias="call_id")
    name: Optional[str] = Field(default=None, alias="name")
    type: Optional[str] = Field(default="function_call", alias="type")
    id: Optional[str] = Field(default=None, alias="id")
    status: Optional[str] = Field(default=None, alias="status")
    pass


