"""
response_response_output_message automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
from .response_response_output import ResponseResponseOutput


# An output message from the model.
class ResponseResponseOutputMessage(ResponseResponseOutput):
    content: Optional[List[str]] = Field(default=None, alias="content")
    id: Optional[str] = Field(default=None, alias="id")
    role: Optional[str] = Field(default=None, alias="role")
    status: Optional[str] = Field(default=None, alias="status")
    type: Optional[str] = Field(default="message", alias="type")
    pass


