"""
response_response automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
from .response_response_error import ResponseResponseError
from .response_response_output import ResponseResponseOutput
from .response_response_output_function_call import ResponseResponseOutputFunctionCall
from .response_response_output_message import ResponseResponseOutputMessage


class ResponseResponse(BaseModel):
    created_at: Optional[int] = Field(default=None, alias="created_at")
    error: Optional[ResponseResponseError] = Field(default=None, alias="error")
    id: Optional[str] = Field(default=None, alias="id")
    incomplete_details: Optional[str] = Field(default=None, alias="incomplete_details")
    object: Optional[str] = Field(default="response", alias="object")
    output: Optional[List[Annotated[Union[Annotated[ResponseResponseOutputFunctionCall, Tag('function_call')], Annotated[ResponseResponseOutputMessage, Tag('message')]], Field(discriminator='type')]]] = Field(default=None, alias="output")
    previous_response_id: Optional[str] = Field(default=None, alias="previous_response_id")
    pass


