"""
response_request_input_message automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
from .response_request_input import ResponseRequestInput


class ResponseRequestInputMessage(ResponseRequestInput):
    content: Optional[str] = Field(default=None, alias="content")
    role: Optional[str] = Field(default=None, alias="role")
    type: Optional[str] = Field(default="message", alias="type")
    pass


