"""
response_request_tool_function automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
from .response_request_tool import ResponseRequestTool


# Defines a function in your own code the model can choose to call.
class ResponseRequestToolFunction(ResponseRequestTool):
    name: Optional[str] = Field(default=None, alias="name")
    parameters: Optional[Any] = Field(default=None, alias="parameters")
    strict: Optional[bool] = Field(default=None, alias="strict")
    type: Optional[str] = Field(default="function", alias="type")
    description: Optional[str] = Field(default=None, alias="description")
    pass


