"""
response_request_input_mcp_list_tools automatically generated by SDKgen please do not edit this file manually
https://sdkgen.app
"""

from pydantic import BaseModel, Field, GetCoreSchemaHandler, Tag
from pydantic_core import CoreSchema, core_schema
from typing import Any, Dict, Generic, List, Optional, TypeVar, Annotated, Union
from .response_request_input import ResponseRequestInput
from .response_mcp_tool import ResponseMCPTool


# A list of tools available on an MCP server.
class ResponseRequestInputMcpListTools(ResponseRequestInput):
    id: Optional[str] = Field(default=None, alias="id")
    server_label: Optional[str] = Field(default=None, alias="server_label")
    tools: Optional[List[ResponseMCPTool]] = Field(default=None, alias="tools")
    error: Optional[str] = Field(default=None, alias="error")
    type: Optional[str] = Field(default="mcp_list_tools", alias="type")
    pass


